# Basic Settings
output:
  directory: "openinsiderData/data"
  filename: "insider_trades.csv"
  format: "csv"

# Scraping Settings
scraping:
  start_year: 2025
  start_month: 1
  max_workers: 10
  retry_attempts: 3
  timeout: 30

# Filter Settings
filters:
  min_transaction_value: 0
  transaction_types: []
  exclude_companies: []
  include_companies: []
  min_shares_traded: 0

# Logging Settings
logging:
  level: "INFO"
  file: "openinsider.log"
  rotate_logs: true
  max_log_size: 10

# Cache Settings
cache:
  enabled: true
  directory: ".cache"
  max_age: 24
